site_name: WhiteIron
site_url: https://jonasmcferreira.github.io/whiteiron/

nav:
  - Home: index.md

  - Settings:
      - Overview: settings.md
      - Jhed Wasteland:
          - Setting: jhed-wasteland/setting.md
          - History & Past: jhed-wasteland/past.md
          - Factions: jhed-wasteland/independent-factions.md
          - Netrus: jhed-wasteland/netrus.md
          - Villages: jhed-wasteland/four-villages.md
          - Thieves' Key: jhed-wasteland/thieves_key.md
          - Weather: jhed-wasteland/weather.md
          - Mechanics: jhed-wasteland/mechanics.md
          - Monster Types: jhed-wasteland/monter-types.md
          - Encounters: jhed-wasteland/encounters.md
          - Magic Items: jhed-wasteland/magic-items.md
          - Adventures: jhed-wasteland/adventures.md
          - Player Handout: jhed-wasteland/player-handout.md
          - Story Hooks: jhed-wasteland/story-hooks.md
      - Lusitania:
          - World Primer: lusitania/00-lusitania.md
          - Campaign Overview: lusitania/01-campaign.md
          - Pantheon: lusitania/02-pantheon.md
          - Locations: lusitania/03-locations.md
          - Magic System: lusitania/04-lusitanian-magic-system.md
      - Phandelver: phandelver/phandelver.md
  - Subclasses:
      - Overview: subclasses.md
      - Path of the Breaker: subclasses/path-of-the-breaker.md
      - Wrangler: subclasses/wrangler.md
  - Abstract Concepts:
      - Powerclass Theory: abstract/powerclass.md
  - Items: items.md
  - Experiments: experiments.md

    
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png  # Optional – same image as favicon for now
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Ancizar Sans
    code: Ancizar Serif
  features:
    - navigation.footer
    - navigation.path
    - navigation.sections
    - toc.follow
    - toc.integrate
  
plugins:
  - search
  - glightbox

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jonasmcferreira/whiteiron
  generator: false

