site_name: WhiteIron
site_url: https://jonasmcferreira.github.io/whiteiron/

nav:
  - Home: index.md
  - Settings:
      - Overview: settings.md
  - Subclasses:
      - All Subclasses: subclasses.md
  - Items:
      - Item List: items.md
  - Experiments:
      - Rule Tests: experiments.md

    
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png  # Optional – same image as favicon for now
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Ancizar Sans
    code: Ancizar Serif
  features:
    - navigation.footer
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.indexes 
    - toc.follow
    - toc.integrate

plugins:
  - search
  - glightbox

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jonasmcferreira/whiteiron
  generator: false

