site_name: WhiteIron
site_url: https://jonasmcferreira.github.io/whiteiron/

nav:
  - Home: index.md
  - Campaign Settings:
      - campaign-settings/index.md
      - jhed-wasteland/setting.md
      - lusitania/index.md
  - Subclasses:
      - subclasses/index.md
      - Path of the Breaker: subclasses/path-of-the-breaker.md
      - Wrangler: subclasses/wrangler.md
  - Magic Items: 
    - magic-items/index.md
  - Experiments: 
    - experiments/index.md


    
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png  # Optional – same image as favicon for now
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Ancizar Sans
    code: Ancizar Serif
  features:
    - navigation.path
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.tabs
    - navigation.indexes 
    - toc.follow
    - toc.integrate
  
plugins:
  - search
  - glightbox

extra_css:
  - style.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jonasmcferreira/whiteiron
  generator: false

